# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f51186e427e2f11572ed4b6338058c61215c2a65b2fa5b873f69ff4f09a2e65d53d12d96637fd64302ff5286505b564d057444b8814c43f873f5bb315b776c00

test:
  secret_key_base: e31524cf170facac6fefd046777a8da47a3ef4dcabd9086c92cf53572ad4fc5aefc4454bf2997b5331713b60ca9feb2a447b4c7c3ba469e4eb6229909feb5cad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
